= Readme for `yStr` -- Yu ZJ's Implementation of Commonly-Used Bioinformatics String Algorithms
:icons: font
:toc:

WARNING: Work-in-progress, do not use.

Here contains some Java 17 implementations over commonly used bioinformatics string algorithms.

== What We Have So Far

=== Checksum Algorithms

. https://wiki.osdev.org/CRC32[CRC32].

=== Hashing Algorithms

. Rabin-Karp-compatible rolling hashes, including polynomial hashes and https://doi.org/10.1093/bioinformatics/btw397[ntHash version 1].

=== Encoders/Decoders

. A simple 4-bit nucleotide encoder.
. A 2-bit nucleotide encoder, resembling the http://genome.ucsc.edu/FAQ/FAQformat.html#format7[UCSC 2bit format].

=== Demonstration Projects

. A simple seed-and-extend algorithm using `ntHash` for hashing. Currently only construction of genomic index was finished.

== Getting `yStr` In Your Project

Currently, we haven't published this module on https://central.sonatype.com/[Maven Central]. However, you may still use it inside your own project if you use Gradle as your build system.

// TODO: Guide.
