= Development Guide

== Requirements

Of course, you need Gradle and JDK. See xref:intro.adoc[] for details.

The integration tests and benchmark bundles largely rely on files available on external sites. To work with them, you need:

* https://www.gnu.org/software/bash/[GNU Bash], 4.5 or above.
* https://www.gnu.org/software/gzip/[GNU GZip] or equivalent.
* https://www.gnu.org/software/make/[GNU Make]. BSD Make will not work.
* https://www.gnu.org/software/coreutils/[GNU CoreUtils] or equivalent. Should at least provide `base64` and `sha256sum` utility.
* https://github.com/samtools/samtools[SAMtools] and (possibly) https://github.com/samtools/tabix[Tabix].
* https://curl.se[Curl], for downloading files.

The formatter used in this project will require the following external binaries:

* https://github.com/patrickvane/shfmt[`shfmt`], version {shfmt-ver}.

== Git

Clone this repository from {github-url}.

== List of Files and Folders

The project root is populated with the following folders:

* {github-url}/tree/master/.idea[`.idea`]: Jetbrains IntelliJ IDEA configurations.
* {github-url}/tree/master/benchmark_out[`benchmark_out`]: Output of generated by all Java Microbenchmark Harness.
* {github-url}/tree/master/gradle[`gradle`]: Simplified Gradle Wrapper. By default, Tencent Mirror was used to speed up download Gradle distributions in China.
* {github-url}/tree/master/src[`src`]: Source files for documentations and miscellaneous tasks.
* {github-url}/tree/master/src_pending[`src_pending`]: Source files staged for further use.
* {github-url}/tree/master/test[`test`]: Test data, either local or remote.
* {github-url}/tree/master/ystr_core[`ystr_core`]: The core yStr module. See xref:ystr-core/index.adoc[].
* {github-url}/tree/master/ystr_demo[`ystr_demo`]: The yStr demo module.

== Software Engineering

== Testing

=== External Test Data

Data from external sources are stored in {github-url}/tree/master/test[`test`]. Refer to {github-url}/tree/master/test/Readme.adoc[Readme] at that directory for more details. All external files were stored with their checksums to ensure integrity.

== Performance

=== Reduce Copy

=== Reduce the Creation of Small Objects

=== Use Faster Alternatives while Processing Containers

=== Get a Faster JVM

If you're working under GNU/Linux, using https://docs.azul.com/prime/#azul-zing-builds-of-openjdk[Azul Zing Builds of OpenJDK] could get a considerable performance boost over conventional OpenJDK. It is free to download for developmental use.

=== Resources on Enhanced Performance
