package com.github.yu_zhejian.ystr.rolling_hash;

import java.util.Iterator;

/**
 * Interface for Rabin-Karp rolling hash algorithm.
 *
 * @param <T> Data type generated by the rolling hash. Recommended to be {@link Long} for 64-bit
 *     hash and {@link Integer} for 32-bit hash.
 */
public interface RollingHashInterface<T extends Number> extends Iterator<T> {}
